[tool.neuralshield.pipeline_order]
order = [
    "neuralshield.preprocessing.steps.00_framing_cleanup:FramingCleanup",
    "neuralshield.preprocessing.steps.01_request_structurer:RequestStructurer",
    "neuralshield.preprocessing.steps.02_header_unfold_obs_fold:HeaderUnfoldObsFold",
    "neuralshield.preprocessing.steps.12_header_field_syntax:HeaderFieldSyntax",
    "neuralshield.preprocessing.steps.03_header_normalization_duplicates:HeaderNormalizationDuplicates",
    "neuralshield.preprocessing.steps.04_whitespace_collapse:WhitespaceCollapse",
    "neuralshield.preprocessing.steps.13_body_framing_inspector:BodyFramingInspector",
    "neuralshield.preprocessing.steps.05_dangerous_characters_script_mixing:DangerousCharactersScriptMixing",
    "neuralshield.preprocessing.steps.06_absolute_url_builder:AbsoluteUrlBuilder",
    "neuralshield.preprocessing.steps.07_unicode_nkfc_and_control:UnicodeNFKCAndControl",
    "neuralshield.preprocessing.steps.08_percent_decode_once:PercentDecodeOnce",
    "neuralshield.preprocessing.steps.09_html_entity_decode_once:HtmlEntityDecodeOnce",
    "neuralshield.preprocessing.steps.10_query_parser_and_flags:QueryParserAndFlags",
    "neuralshield.preprocessing.steps.11_path_structure_normalizer:PathStructureNormalizer",
]
