[tool.neuralshield.pipeline_order]
order = [
  "neuralshield.preprocessing.steps.pre_parse_over_raw:RequestStructurer",
  "neuralshield.preprocessing.steps.pre_parse_over_raw:RemoveFramingArtifacts",
]