[tool.neuralshield.pipeline_order]
order = [
    "neuralshield.preprocessing.steps.00_framing_cleanup:FramingCleanup",
    "neuralshield.preprocessing.steps.01_request_structurer:RequestStructurer",
    "neuralshield.preprocessing.steps.02_bytes_to_unicode:BytesToUnicode",
    "neuralshield.preprocessing.steps.03_unicode_nfkc:UnicodeNFKC",
    "neuralshield.preprocessing.steps.04_percent_decode_once:PercentDecodeOnce",
    "neuralshield.preprocessing.steps.05_html_entity_decode_once:HTMLEntityDecodeOnce",
    "neuralshield.preprocessing.steps.06_query_parser:QueryParser",
    "neuralshield.preprocessing.steps.07_path_structure_normalizer:PathStructureNormalizer",
    "neuralshield.preprocessing.steps.08_header_unfold_obs_fold:HeaderUnfoldObsFold",
    "neuralshield.preprocessing.steps.09_header_normalization:HeaderNormalization",
    "neuralshield.preprocessing.steps.10_whitespace_collapse:WhitespaceCollapse",
    "neuralshield.preprocessing.steps.11_dangerous_chars:DangerousCharsDetector",
    "neuralshield.preprocessing.steps.12_absolute_url_builder:AbsoluteURLBuilder",
    "neuralshield.preprocessing.steps.13_length_bucketing:LengthBucketing",
]