[tool.neuralshield.pipeline_order]
order = [
  "neuralshield.preprocessing.steps.00_framing_cleanup:FramingCleanup",
  "neuralshield.preprocessing.steps.01_request_structurer:RequestStructurer",
  "neuralshield.preprocessing.steps.04_unicode_nfkc:UnicodeNFKC",
  "neuralshield.preprocessing.steps.05_percent_decode_once:PercentDecodeOnce",
  "neuralshield.preprocessing.steps.06_html_entity_decode_once:HTMLEntityDecodeOnce",
  "neuralshield.preprocessing.steps.07_query_parser:QueryProcessor",
  "neuralshield.preprocessing.steps.08_path_structure_normalizer:PathStructureNormalizer",
  "neuralshield.preprocessing.steps.12_dangerous_chars:DangerousCharacterDetector",
]